name: Update recent blog post

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Update the README.md with recent blog posts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          committer_username: github-actions[bot]
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_message: "📗 Update README.md with the latest blog posts"
          readme_path: README.md
          comment_tag_name: BLOG-POST-LIST
          feed_list: "https://ilkeraksoy.dev/atom.xml"
          tag_post_pre_newline: true
          template: "- :writing_hand: [$title]($url) - ($date)"
          date_format: "yyyy/mm/dd"
