name: Update Weather

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update this repo's README with recent weather
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: weather-profile-actions
        uses: bumb7ebee/weather-profile-actions@v1
        with:
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          city-id: 740483
          units: c
          country-code: tr
          readme-path: README.md
